### ISSUE TITLE
Per action middleware options after/before

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/dolman#4]

**Comment by dheavy** [comment]
If I get this feature correctly based on the title...
Validation being already baked in, the first real-world use-case I can think of for this feature is authentication and/or ACL on sets of routes. 
Since several `dolman.router` instances can coexist within the same app you could think of creating different routers acting as a logical group of routes based on the access level (e.g. public, private, or other special access level: `app.use('/admin', authAdminMiddleware, adminRouter)`) right?
There might be other _obvious_ use-cases for after/before filters in routes but my brain is so slow I can't find any right no. 

So as of now, is it really a _sine qua none_ feature? Or maybe you have an example right out of your head.

**Comment by Yomguithereal** [comment]
Yes, for the time being I have dropped the feature as the example you show (as the one displayed in the docs) works quite right for now. I propose that we reopen the subject when we have a real-life issue to solve.

**Comment by Yomguithereal** [comment]
But having the possibility to register middleware for some routes (before validation, I guess) could become handy.

**Comment by Yomguithereal** [comment]
But it would probably be the product of a bad project organization, so I am still pondering it.

**Comment by dheavy** [comment]
All other real-life use cases that come up in my head right now for before/after filters have to do with e.g. models or stuff that are not dealt with at the API layer...
